/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStockOutRouteImport } from './routes/_authenticated/stock-out'
import { Route as AuthenticatedStockInRouteImport } from './routes/_authenticated/stock-in'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOrderRequestRouteImport } from './routes/_authenticated/order-request'
import { Route as AuthenticatedOrderHistoryRouteImport } from './routes/_authenticated/order-history'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePinRouteImport } from './routes/_authenticated/change-pin'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as ApiPublicServerHealthRouteImport } from './routes/api/public/server-health'
import { Route as ApiPublicHooksNightlyBackupRouteImport } from './routes/api/public/hooks/nightly-backup'
import { Route as ApiPublicHooksMirrorSyncRouteImport } from './routes/api/public/hooks/mirror-sync'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockOutRoute = AuthenticatedStockOutRouteImport.update({
  id: '/stock-out',
  path: '/stock-out',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockInRoute = AuthenticatedStockInRouteImport.update({
  id: '/stock-in',
  path: '/stock-in',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrderRequestRoute =
  AuthenticatedOrderRequestRouteImport.update({
    id: '/order-request',
    path: '/order-request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrderHistoryRoute =
  AuthenticatedOrderHistoryRouteImport.update({
    id: '/order-history',
    path: '/order-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePinRoute = AuthenticatedChangePinRouteImport.update({
  id: '/change-pin',
  path: '/change-pin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicServerHealthRoute = ApiPublicServerHealthRouteImport.update({
  id: '/api/public/server-health',
  path: '/api/public/server-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNightlyBackupRoute =
  ApiPublicHooksNightlyBackupRouteImport.update({
    id: '/api/public/hooks/nightly-backup',
    path: '/api/public/hooks/nightly-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMirrorSyncRoute =
  ApiPublicHooksMirrorSyncRouteImport.update({
    id: '/api/public/hooks/mirror-sync',
    path: '/api/public/hooks/mirror-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/change-pin': typeof AuthenticatedChangePinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/order-history': typeof AuthenticatedOrderHistoryRoute
  '/order-request': typeof AuthenticatedOrderRequestRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/stock-in': typeof AuthenticatedStockInRoute
  '/stock-out': typeof AuthenticatedStockOutRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/server-health': typeof ApiPublicServerHealthRoute
  '/api/public/hooks/mirror-sync': typeof ApiPublicHooksMirrorSyncRoute
  '/api/public/hooks/nightly-backup': typeof ApiPublicHooksNightlyBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/change-pin': typeof AuthenticatedChangePinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/order-history': typeof AuthenticatedOrderHistoryRoute
  '/order-request': typeof AuthenticatedOrderRequestRoute
  '/products': typeof AuthenticatedProductsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/stock-in': typeof AuthenticatedStockInRoute
  '/stock-out': typeof AuthenticatedStockOutRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/server-health': typeof ApiPublicServerHealthRoute
  '/api/public/hooks/mirror-sync': typeof ApiPublicHooksMirrorSyncRoute
  '/api/public/hooks/nightly-backup': typeof ApiPublicHooksNightlyBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/change-pin': typeof AuthenticatedChangePinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/order-history': typeof AuthenticatedOrderHistoryRoute
  '/_authenticated/order-request': typeof AuthenticatedOrderRequestRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRoute
  '/_authenticated/stock-in': typeof AuthenticatedStockInRoute
  '/_authenticated/stock-out': typeof AuthenticatedStockOutRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/public/server-health': typeof ApiPublicServerHealthRoute
  '/api/public/hooks/mirror-sync': typeof ApiPublicHooksMirrorSyncRoute
  '/api/public/hooks/nightly-backup': typeof ApiPublicHooksNightlyBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/backups'
    | '/change-pin'
    | '/dashboard'
    | '/health'
    | '/order-history'
    | '/order-request'
    | '/products'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/stock-in'
    | '/stock-out'
    | '/users'
    | '/api/public/server-health'
    | '/api/public/hooks/mirror-sync'
    | '/api/public/hooks/nightly-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/backups'
    | '/change-pin'
    | '/dashboard'
    | '/health'
    | '/order-history'
    | '/order-request'
    | '/products'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/stock-in'
    | '/stock-out'
    | '/users'
    | '/api/public/server-health'
    | '/api/public/hooks/mirror-sync'
    | '/api/public/hooks/nightly-backup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/audit'
    | '/_authenticated/backups'
    | '/_authenticated/change-pin'
    | '/_authenticated/dashboard'
    | '/_authenticated/health'
    | '/_authenticated/order-history'
    | '/_authenticated/order-request'
    | '/_authenticated/products'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shipments'
    | '/_authenticated/stock-in'
    | '/_authenticated/stock-out'
    | '/_authenticated/users'
    | '/api/public/server-health'
    | '/api/public/hooks/mirror-sync'
    | '/api/public/hooks/nightly-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicServerHealthRoute: typeof ApiPublicServerHealthRoute
  ApiPublicHooksMirrorSyncRoute: typeof ApiPublicHooksMirrorSyncRoute
  ApiPublicHooksNightlyBackupRoute: typeof ApiPublicHooksNightlyBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock-out': {
      id: '/_authenticated/stock-out'
      path: '/stock-out'
      fullPath: '/stock-out'
      preLoaderRoute: typeof AuthenticatedStockOutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock-in': {
      id: '/_authenticated/stock-in'
      path: '/stock-in'
      fullPath: '/stock-in'
      preLoaderRoute: typeof AuthenticatedStockInRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order-request': {
      id: '/_authenticated/order-request'
      path: '/order-request'
      fullPath: '/order-request'
      preLoaderRoute: typeof AuthenticatedOrderRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order-history': {
      id: '/_authenticated/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof AuthenticatedOrderHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-pin': {
      id: '/_authenticated/change-pin'
      path: '/change-pin'
      fullPath: '/change-pin'
      preLoaderRoute: typeof AuthenticatedChangePinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/server-health': {
      id: '/api/public/server-health'
      path: '/api/public/server-health'
      fullPath: '/api/public/server-health'
      preLoaderRoute: typeof ApiPublicServerHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nightly-backup': {
      id: '/api/public/hooks/nightly-backup'
      path: '/api/public/hooks/nightly-backup'
      fullPath: '/api/public/hooks/nightly-backup'
      preLoaderRoute: typeof ApiPublicHooksNightlyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mirror-sync': {
      id: '/api/public/hooks/mirror-sync'
      path: '/api/public/hooks/mirror-sync'
      fullPath: '/api/public/hooks/mirror-sync'
      preLoaderRoute: typeof ApiPublicHooksMirrorSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedChangePinRoute: typeof AuthenticatedChangePinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedOrderHistoryRoute: typeof AuthenticatedOrderHistoryRoute
  AuthenticatedOrderRequestRoute: typeof AuthenticatedOrderRequestRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRoute
  AuthenticatedStockInRoute: typeof AuthenticatedStockInRoute
  AuthenticatedStockOutRoute: typeof AuthenticatedStockOutRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedChangePinRoute: AuthenticatedChangePinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedOrderHistoryRoute: AuthenticatedOrderHistoryRoute,
  AuthenticatedOrderRequestRoute: AuthenticatedOrderRequestRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRoute,
  AuthenticatedStockInRoute: AuthenticatedStockInRoute,
  AuthenticatedStockOutRoute: AuthenticatedStockOutRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicServerHealthRoute: ApiPublicServerHealthRoute,
  ApiPublicHooksMirrorSyncRoute: ApiPublicHooksMirrorSyncRoute,
  ApiPublicHooksNightlyBackupRoute: ApiPublicHooksNightlyBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
